name: Auto-commit Prompt Updates

on:
  push:
    paths:
      - '**/.prompt.md'

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'  # Prevent infinite loops
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Git Identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      
      - name: Commit Changes
        run: |
          git add "**/.prompt.md"
          git commit -m "Auto-update prompt with new pitfalls [skip ci]"
          git push
