name: Issue Automation

on:
  issues:
    types: [opened, edited, reopened]
  pull_request:
    types: [opened, edited, reopened]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-label issues
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const payload = context.payload;
            
            const isIssue = !!payload.issue;
            const item = isIssue ? payload.issue : payload.pull_request;
            const itemNumber = item.number;
            const itemType = isIssue ? 'issue' : 'pull request';
            const content = item.body || '';
            const title = item.title || '';

            console.log(`Processing ${itemType} #${itemNumber}: ${title}`);
            
            // Define patterns to match and their corresponding labels
            const patterns = [
              { pattern: /build|pipeline|ci\/cd|workflow|github action/i, label: 'ci-cd' },
              { pattern: /bug|error|fix|issue|problem|fail/i, label: 'bug' },
              { pattern: /feature|enhancement|improvement/i, label: 'enhancement' },
              { pattern: /doc|documentation|readme/i, label: 'documentation' },
              { pattern: /test|testing|unittest|integration test/i, label: 'testing' },
              { pattern: /semantic model|power bi/i, label: 'semantic-models' },
              { pattern: /urgent|critical|important|high priority/i, label: 'high-priority' },
              { pattern: /question|help|guidance|clarification/i, label: 'question' }
            ];
            
            // Collect labels to add based on content
            const labelsToAdd = [];
            for (const { pattern, label } of patterns) {
              if (pattern.test(title) || pattern.test(content)) {
                labelsToAdd.push(label);
                console.log(`Matched pattern for label: ${label}`);
              }
            }
            
            // Add labels if any matches found
            if (labelsToAdd.length > 0) {
              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number: itemNumber,
                labels: labelsToAdd
              });
              
              console.log(`Added labels: ${labelsToAdd.join(', ')}`);
            }
            
      - name: Add needs-review label for PRs
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.payload.pull_request.number;
            
            await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: prNumber,
              labels: ['needs-review']
            });
